# -*- coding: utf-8 -*-
"""Shikibetsu.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qR28l9FH1hURCEf6C_W_ZZgyxXG0BfDD
"""

import torch
import torchvision.models as models

#Siamese(2 parallel networks) Network which will take a pair of input images for comparison and 
#identifying whether they are from the same person or not.

#The base network is GoogLeNet pre-trained on Imagenet database.
basenet1 = models.googlenet(pretrained=True)
basenet2 = models.googlenet(pretrained=True)